version: '3.1'

services:

  sqlite:
    image: nouchka/sqlite3:latest
    platform: linux/amd64
    stdin_open: true
    tty: true
    volumes:
      - ./database:/var/lib/sqlite/data
    environment:
      - SQLITE_USER=sqlite
      - SQLITE_PASSWORD=sqlite
      - SQLITE_DB=sqlite
    ports:
      - 5432:5432


